"""Add analytics_summary table for audit metrics

Revision ID: 0002_analytics_summary
Revises: 0001_initial_schema
Create Date: 2024-12-20 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_analytics_summary'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_summary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_log_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('unique_documents', sa.Integer(), nullable=False),
    sa.Column('avg_source_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_summary_created_at'), 'analytics_summary', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_summary_query_log_id'), 'analytics_summary', ['query_log_id'], unique=False)
    op.create_index(op.f('ix_analytics_summary_workspace_id'), 'analytics_summary', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_summary_workspace_id'), table_name='analytics_summary')
    op.drop_index(op.f('ix_analytics_summary_query_log_id'), table_name='analytics_summary')
    op.drop_index(op.f('ix_analytics_summary_created_at'), table_name='analytics_summary')
    op.drop_table('analytics_summary')
    # ### end Alembic commands ###