"""Add financial intelligence tables

Revision ID: 0003_financial_intelligence
Revises: 0002_add_analytics_summary
Create Date: 2024-12-20 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003_financial_intelligence'
down_revision: Union[str, None] = '0002_analytics_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create document_comparisons table
    op.create_table('document_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('document_a_id', sa.String(length=36), nullable=False),
    sa.Column('document_b_id', sa.String(length=36), nullable=False),
    sa.Column('financial_metrics_comparison', sa.Text(), nullable=True),
    sa.Column('sentiment_comparison', sa.Text(), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('total_metrics_compared', sa.Integer(), nullable=False),
    sa.Column('metrics_with_significant_changes', sa.Integer(), nullable=False),
    sa.Column('overall_sentiment_shift', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_a_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_b_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_comparisons_created_at'), 'document_comparisons', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_comparisons_user_id'), 'document_comparisons', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_comparisons_workspace_id'), 'document_comparisons', ['workspace_id'], unique=False)
    
    # Create sentiment_analysis table
    op.create_table('sentiment_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('positive_score', sa.Float(), nullable=False),
    sa.Column('neutral_score', sa.Float(), nullable=False),
    sa.Column('negative_score', sa.Float(), nullable=False),
    sa.Column('dominant_sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('sections_analyzed', sa.Integer(), nullable=False),
    sa.Column('section_sentiments', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analysis_created_at'), 'sentiment_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentiment_analysis_document_id'), 'sentiment_analysis', ['document_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analysis_document_id'), table_name='sentiment_analysis')
    op.drop_index(op.f('ix_sentiment_analysis_created_at'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    
    op.drop_index(op.f('ix_document_comparisons_workspace_id'), table_name='document_comparisons')
    op.drop_index(op.f('ix_document_comparisons_user_id'), table_name='document_comparisons')
    op.drop_index(op.f('ix_document_comparisons_created_at'), table_name='document_comparisons')
    op.drop_table('document_comparisons')
    # ### end Alembic commands ###